### ISSUE TITLE
Rand() panics when passed MaxDuration.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/linger#18]
Because the current implementation uses `rand.Int63n()`, it adds 1 to the upper bound to try to make the range inclusive, but this causes an overflow when the upper bound is `MaxDuration`.

**Comment by jmalloc** [comment]
There's no function in the standard `rand` package that can return an `int64` within a range, that can actually span the full space of an `int64`.

**Comment by danilvpetrov** [comment]
Do you need to deal with positive `time.Duration` only, right? So ideally the range should be from time.Duration(0) to time.Duration(MaxInt32), I might be wrong though.

**Comment by jmalloc** [comment]
I would prefer if it JustWorked(tm) with any valid `time.Duration` values.
